# Generated by Django 5.1.6 on 2025-03-01 19:55

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsightCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=200)),
                ('banner_subtitle', models.TextField()),
                ('banner_image', models.ImageField(upload_to='banners/')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('industry', 'Industry'), ('capability', 'Capability')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurInsights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='insights/')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights', to='industries.insightcategory')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industries.page')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('link', models.CharField(max_length=200)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industries.page')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industries.service'),
        ),
        migrations.AddField(
            model_name='insightcategory',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='industries.service'),
        ),
        migrations.CreateModel(
            name='WhatWeDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industries.page')),
            ],
        ),
    ]
