# Generated by Django 5.1.6 on 2025-03-02 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='link',
        ),
    ]
